# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vla.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvla.proto\x12\x03vla\"I\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63\x61mera_name\x18\x02 \x01(\t\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\"P\n\x0ePredictRequest\x12\x1a\n\x06images\x18\x01 \x03(\x0b\x32\n.vla.Image\x12\x13\n\x0binstruction\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x03(\x02\"J\n\x0fPredictResponse\x12\x0f\n\x07\x61\x63tions\x18\x01 \x03(\x02\x12\x12\n\naction_dim\x18\x02 \x01(\x05\x12\x12\n\nchunk_size\x18\x03 \x01(\x05\"\x0e\n\x0cResetRequest\"\x1f\n\rResetResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2r\n\nVLAService\x12\x34\n\x07Predict\x12\x13.vla.PredictRequest\x1a\x14.vla.PredictResponse\x12.\n\x05Reset\x12\x11.vla.ResetRequest\x1a\x12.vla.ResetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vla_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGE']._serialized_start=18
  _globals['_IMAGE']._serialized_end=91
  _globals['_PREDICTREQUEST']._serialized_start=93
  _globals['_PREDICTREQUEST']._serialized_end=173
  _globals['_PREDICTRESPONSE']._serialized_start=175
  _globals['_PREDICTRESPONSE']._serialized_end=249
  _globals['_RESETREQUEST']._serialized_start=251
  _globals['_RESETREQUEST']._serialized_end=265
  _globals['_RESETRESPONSE']._serialized_start=267
  _globals['_RESETRESPONSE']._serialized_end=298
  _globals['_VLASERVICE']._serialized_start=300
  _globals['_VLASERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
